apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment-1
  namespace: web-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-1
  template:
    metadata:
      labels:
        app: spring-app-1
    spec:
      containers:
        - name: spring-app-1
          image: hello-springboot:7.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service.web-namespace.svc.cluster.local:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 5


          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
