apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: web-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_DATABASE: YXBwZGI=
  MYSQL_USER: YXBwdXNlcg==
  MYSQL_PASSWORD: YXBwcGFzcw==