apiVersion: v1
kind: Service
metadata:
  name: spring-service-1
  namespace: web-namespace
spec:
  type: NodePort
  selector:
    app: spring-app-1
  ports:
    - port: 80
      targetPort: 8080
      # NodePort must be within the range configured for your cluster (default 30000-32767)
      nodePort: 30009